name: Push to EEA Repo via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EEA_GITHUB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to EEA Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git remote add eea git@github.com:eea/natura2000_portal_frontend.git
          git push --force eea main
